services:
  dev-env:
    build:
      context: .
      dockerfile: dev-env.Dockerfile
    network_mode: host
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/home/vscode/.aws:ro
      - ~/.minikube:/home/vscode/.minikube
    environment:
      - AWS_PROFILE=default
    user: vscode

  kubectl:
    image: bitnami/kubectl:1.32.3
    network_mode: host
    volumes:
      - ~/.kube:/root/.kube
    entrypoint: ["sleep", "infinity"]
  
  aws-cli:
    image: amazon/aws-cli:latest
    network_mode: host
    volumes:
      - ~/.aws:/root/.aws:ro
      - ..:/workspace
    entrypoint: ["sleep", "infinity"]